# Generated by Django 5.0.7 on 2024-07-21 10:06

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('mrn', models.CharField(max_length=100)),
                ('physician_name', models.CharField(max_length=25)),
                ('phone', phone_field.models.PhoneField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorChargeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HL7_App.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EncounterChargesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HL7_App.patientmodel')),
            ],
        ),
    ]
