# Generated by Django 5.0.7 on 2024-07-21 10:08

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HL7_App', '0003_alter_patientmodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
