# Generated by Django 5.0.7 on 2024-07-21 10:10

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HL7_App', '0004_alter_patientmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='physician_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
