# Generated by Django 5.0.7 on 2024-07-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HL7_App', '0005_alter_patientmodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='encounterchargesmodel',
            table='EncounterCharges',
        ),
        migrations.AlterModelTable(
            name='errorchargemodel',
            table='ErrorCharge',
        ),
        migrations.AlterModelTable(
            name='patientmodel',
            table='Patient',
        ),
    ]
