# Generated by Django 5.0.7 on 2024-07-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HL7_App', '0006_alter_encounterchargesmodel_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorchargemodel',
            name='patient',
        ),
    ]
